// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Service achat et paiement', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('4. Accex au panier', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect(1546, 822)
    await driver.findElement(By.linkText("Samsung galaxy s6")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added")
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.linkText("Delete")).click()
    await driver.findElement(By.css(".btn-success")).click()
    {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
  it('6. Confirmation du paiement', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect(1546, 822)
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Habib Sellami")
    await driver.findElement(By.id("country")).sendKeys("Tunisia")
    await driver.findElement(By.id("city")).sendKeys("Paris-l\'Hôpital")
    await driver.findElement(By.css(".form-group:nth-child(5)")).click()
    await driver.findElement(By.id("card")).click()
    await driver.findElement(By.id("card")).sendKeys("555555555555")
    await driver.findElement(By.css(".form-group:nth-child(6)")).click()
    await driver.findElement(By.id("month")).click()
    await driver.findElement(By.id("month")).sendKeys("12")
    await driver.findElement(By.id("year")).click()
    await driver.findElement(By.id("year")).sendKeys("2002")
    await driver.findElement(By.css("#orderModal .btn-primary")).click()
    {
      const element = await driver.findElement(By.css("#orderModal .btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".confirm")).click()
  })
  it('3. Ajout d'un produit au cart', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect(1546, 822)
    await driver.findElement(By.linkText("Samsung galaxy s6")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added")
  })
})
