// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Service exposition', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('8. Exploration des pages', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect(1546, 822)
    await driver.findElement(By.linkText("Contact")).click()
    await driver.findElement(By.css("#exampleModal span")).click()
    await driver.findElement(By.linkText("About us")).click()
    {
      const element = await driver.findElement(By.linkText("About us"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#videoModal .modal-header span")).click()
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.id("login2")).click()
    await driver.findElement(By.css("#logInModal .modal-header")).click()
    await driver.findElement(By.css("#logInModal span")).click()
    await driver.findElement(By.id("signin2")).click()
    {
      const element = await driver.findElement(By.id("signin2"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#signInModal span")).click()
    await driver.findElement(By.css(".active > .nav-link")).click()
    await driver.findElement(By.id("cartur")).click()
  })
  it('7. Recherche', async function() {
  })
  it('2. Parcours des produits', async function() {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect(1546, 822)
    await driver.findElement(By.id("itemc")).click()
    await driver.findElement(By.linkText("Monitors")).click()
    await driver.findElement(By.linkText("Laptops")).click()
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
